import { StyleSheet } from "react-native";

export const PLAYER_SIZE = 50;
export const CENTER_SIZE = 80;
export const RADIUS = 130;
export const CENTER_X = 180;
export const CENTER_Y = 120;

export const gameComponentStyles = StyleSheet.create({
    outerContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'transparent',
        width: '100%',
        height: '55%',
    },
    boardContainer: {
        width: 360,
        height: 240,
        position: 'relative',
    },
    playerCircleContainer: {
        position: 'absolute',
        alignItems: 'center',
    },
    playerName: {
        color: '#fff',
        fontSize: 12,
        textAlign: 'center',
        marginBottom: 2,
        marginTop: 0,
        fontWeight: '600',
    },
    playerNameCurrentTurn: {
        color: '#FFD700',
        fontSize: 12, // Same size as regular player name
        textAlign: 'center',
        marginBottom: 2,
        marginTop: 0,
        fontWeight: 'bold',
        textShadowColor: '#000',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },
    avatarContainer: {
        width: PLAYER_SIZE,
        height: PLAYER_SIZE,
        borderRadius: PLAYER_SIZE / 2,
        backgroundColor: '#4A0E72',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#fff',
        overflow: 'hidden',
    },
    avatarContainerCurrentTurn: {
        width: PLAYER_SIZE + 4,
        height: PLAYER_SIZE + 4,
        borderRadius: (PLAYER_SIZE + 4) / 2,
        backgroundColor: '#4A0E72',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: '#FFD700',
        overflow: 'hidden',
        shadowColor: '#FFD700',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 8,
        elevation: 10,
    },
    avatar: {
        width: PLAYER_SIZE - 8,
        height: PLAYER_SIZE - 8,
        borderRadius: (PLAYER_SIZE - 8) / 2,
        resizeMode: 'cover',
    },
    avatarCurrentTurn: {
        width: PLAYER_SIZE - 4,
        height: PLAYER_SIZE - 4,
        borderRadius: (PLAYER_SIZE - 4) / 2,
        resizeMode: 'cover',
    },
    centerCircleContainer: {
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 2,
        backgroundColor: 'transparent',
    },
    centerCircleImage: {
        width: CENTER_SIZE,
        height: CENTER_SIZE,
    },
    centerCircleText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
        zIndex: 1,
        textShadowColor: '#000',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
    playerStatusContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 2,
    },
    playerStatusText: {
        color: '#fff',
        fontSize: 12,
        marginHorizontal: 1,
    },
    typingContainer: {
        position: 'absolute',
        top: -25,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255, 215, 0, 0.9)',
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 12,
        minWidth: 60,
        minHeight: 20,
    },
    typingText: {
        color: '#4A0E72',
        fontSize: 10,
        fontWeight: 'bold',
        textAlign: 'center',
        flexShrink: 1,
    },
    turnIndicator: {
        position: 'absolute',
        top: -35,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255, 215, 0, 0.95)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#FFA500',
        minWidth: 70,
        minHeight: 22,
    },
    turnIndicatorText: {
        color: '#4A0E72',
        fontSize: 9,
        fontWeight: 'bold',
        textAlign: 'center',
        flexShrink: 1,
    },
    pulseGlow: {
        position: 'absolute',
        width: PLAYER_SIZE + 20,
        height: PLAYER_SIZE + 20,
        borderRadius: (PLAYER_SIZE + 20) / 2,
        backgroundColor: 'rgba(255, 215, 0, 0.3)',
        top: -10,
        left: -10,
    },
});